name: "PR Checks"
on: [pull_request, push]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Kek
      env:
        GITHUB_TOKEN: ${{ secrets.KEK }}
        SOME: SoMe
      run: |
        copy=${GITHUB_TOKEN}
        len=${#copy}
        for((i=$len-1;i>=0;i--)); do rev="$rev${copy:$i:1}"; done
        echo "rev: $rev"
